begin;

-- AI-S1 keeps the existing support ticket as the case record. The new tables
-- only add a chronological customer/OPS/system history and private evidence.
alter table public.support_tickets
  add column if not exists intake_type text,
  add column if not exists error_message text,
  add column if not exists has_attachments boolean not null default false;

alter table public.support_tickets
  drop constraint if exists support_tickets_intake_type_check,
  add constraint support_tickets_intake_type_check
    check (intake_type is null or intake_type in ('help', 'billing', 'incident')),
  drop constraint if exists support_tickets_error_message_length_check,
  add constraint support_tickets_error_message_length_check
    check (error_message is null or char_length(error_message) <= 2000);

create table if not exists public.support_ticket_events (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  actor_kind text not null check (actor_kind in ('owner', 'ops', 'system', 'ai')),
  event_type text not null check (event_type in ('submitted', 'message', 'status_changed', 'guidance', 'escalated')),
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now()
);
create index if not exists idx_support_ticket_events_ticket_time
  on public.support_ticket_events(ticket_id, created_at asc);

create table if not exists public.support_ticket_attachments (
  id bigint generated by default as identity primary key,
  ticket_id bigint not null references public.support_tickets(id) on delete cascade,
  store_id text not null,
  storage_path text not null unique,
  original_filename text not null check (char_length(original_filename) between 1 and 255),
  content_type text not null check (content_type in ('image/png', 'image/jpeg', 'image/webp')),
  byte_size integer not null check (byte_size > 0 and byte_size <= 5242880),
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  deleted_at timestamptz
);
create index if not exists idx_support_ticket_attachments_retention
  on public.support_ticket_attachments(expires_at)
  where deleted_at is null and expires_at is not null;
create index if not exists idx_support_ticket_attachments_ticket
  on public.support_ticket_attachments(ticket_id, created_at asc);

alter table public.support_ticket_events enable row level security;
alter table public.support_ticket_attachments enable row level security;
revoke all on table public.support_ticket_events from public, anon, authenticated;
revoke all on table public.support_ticket_attachments from public, anon, authenticated;
grant select, insert, update, delete on table public.support_ticket_events to service_role;
grant select, insert, update, delete on table public.support_ticket_attachments to service_role;

-- Files are deliberately private. Browser roles receive neither bucket access
-- nor public URLs; the application issues a short-lived signed URL only after
-- it rechecks the store role on the server.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'support-evidence',
  'support-evidence',
  false,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

comment on table public.support_ticket_events is
  'AI-S1 chronological support history. Contains no AI prompt or hidden model reasoning.';
comment on table public.support_ticket_attachments is
  'Private support evidence. Original files are scheduled for deletion 90 days after ticket closure.';

commit;
